// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jchthyffnllwuvywbtvs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjaHRoeWZmbmxsd3V2eXdidHZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMTAxMjksImV4cCI6MjA1ODg4NjEyOX0.lYb1n6kapRwxQUvX32I4Qe3j9h_fdfE12v3xXLYJz80";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);